<?php

declare(strict_types=1);

use Drupal\Core\StringTranslation\PluralTranslatableMarkup;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Clear entity caches after removing custom node entity and storage classes.
 */
function omnipedia_core_update_106001(): void {

  /** @var \Drupal\Core\Entity\EntityTypeManagerInterface The Drupal entity type manager. */
  $entityTypeManager = \Drupal::service('entity_type.manager');

  // Don't do anything if our old node entity class is not the current entity
  // class. This can happen if updates are run in an unexpected order or
  // something else has occurred that we didn't anticipate.
  if (!$entityTypeManager->getStorage(
    'node',
  )->getEntityClass() === 'Drupal\omnipedia_core\Entity\Node') {
    return;
  }

  // This forces a rebuild of the container so that our event subscriber that
  // previously replaced the node entity and storage classes is no longer
  // referenced, since it's been removed.
  \Drupal::service('kernel')->invalidateContainer();

  $entityTypeManager->clearCachedDefinitions();

  $entityTypeManager->getStorage('node')->resetCache();

}

/**
 * Clear typed entity cached definitions to pick up taxonomy term repository.
 */
function omnipedia_core_update_106002(): void {

  \Drupal::service(
    'plugin.manager.typed_entity_repository',
  )->clearCachedDefinitions();

}

/**
 * Remove any tracked wiki node data referencing non-existent nodes.
 */
function omnipedia_core_update_106003(): TranslatableMarkup {

  $nodeStorage = \Drupal::service('entity_type.manager')->getStorage('node');

  $state = \Drupal::service('state');

  $stateNodeDates = $state->get('omnipedia.wiki_node_dates');

  $stateNodeInfo = $state->get('omnipedia.wiki_node_info');

  $stateNodeTitles = $state->get('omnipedia.wiki_node_titles');

  $existingIds = array_values(($nodeStorage->getQuery())
    ->condition('type', 'wiki_page')
    ->accessCheck(false)
    ->execute());

  $nonExistentIds = [];

  foreach ($stateNodeDates as $date => $nids) {

    // $existing = array_filter($nids, fn($nid) => isset($existingIds[$nid]));
    $existing = array_intersect($nids, $existingIds);

    if (count($nids) === count($existing)) {
      continue;
    }

    $nonExisting = array_diff($nids, $existing);

    $nonExistentIds = array_merge($nonExistentIds, $nonExisting);

    $stateNodeDates[$date] = array_intersect($stateNodeDates[$date], $existing);

  }

  $state->set('omnipedia.wiki_node_dates', $stateNodeDates);

  $nonExistentInfo = array_diff_key(
    $stateNodeInfo, $existingIds,
  );

  foreach ($nonExistentInfo as $nid => $info) {

    $nonExistentIds[] = $nid;

    unset($stateNodeInfo[$nid]);

  }

  $state->set('omnipedia.wiki_node_info', $stateNodeInfo);

  $nonExistentTitles = array_diff_key(
    $stateNodeTitles, $existingIds,
  );

  foreach ($nonExistentTitles as $nid => $title) {

    $nonExistentIds[] = $nid;

    unset($nonExistentTitles[$nid]);

  }

  $state->set('omnipedia.wiki_node_titles', $stateNodeTitles);

  $nonExistentIds = array_unique($nonExistentIds);

  if (count($nonExistentIds) === 0) {

    return new TranslatableMarkup(
      'Did not find any references to non-existent wiki nodes.',
    );

  }

  return new PluralTranslatableMarkup(
    count($nonExistentIds),
    'Found and fixed a reference to 1 non-existent wiki node.',
    'Found and fixed references to @count non-existent wiki nodes.',
  );

  // \Drupal::service('state')->set(
  //   'omnipedia.wiki_node_dates',
  //   array_map(\Drupal::service('state')->get('omnipedia.wiki_node_dates'))
  // );

}
